# openapi: 3.0.0
# info:
# #   title: Swagger Petstore - OpenAPI 3.0
# #   termsOfService: http://swagger.io/terms/
# #   contact:
# #     email: apiteam@swagger.io
# #   license:
# #     name: Apache 2.0
# #     url: http://www.apache.org/licenses/LICENSE-2.0.html
# #   version: 1.0.11
# # externalDocs:
# #   description: Find out more about Swagger
# #   url: http://swagger.io
# # servers:
# #   - url: https://petstore3.swagger.io/api/v3
# # tags:
# #   - name: pet
# #     description: Everything about your Pets
# #     externalDocs:
# #       description: Find out more
# #       url: http://swagger.io
# #   - name: store
# #     description: Access to Petstore orders
# #     externalDocs:
# #       description: Find out more about our store
# #       url: http://swagger.io
# #   - name: user
# #     description: Operations about user

# tags:
#   - name: num

# get:
#   description: None
# paths:
#   /prime/{number}:
#     get:
#       tags:
#         - name: number
#       parameters:
#         - name: number
#           in: path
#           required: true
#           schema:
#             type: integer
#       responses:
#         '200':
#           description: successful operation
#         '400':
#           description: Invalid ID supplied
#         '404':
#           description: Page not found
    
openapi: 3.0.0
tags:
  - name: Get all prime numbers
get:
  
  description: None

parameters:
    -in : "body"
    name: "num"
    description: "Enter a number"
    required: true
    schema:
      type: "integer"
paths:
  /random/{num}:
    get:
      parameters:
        - in: num
          name: num   # Note the name is the same as in the path
          required: true
          type: integer
          minimum: 1
          description: The user ID.
       

responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error
# parameters:
#       - name: "num"
#         type: "integer"
# paths:
#   /random/{num}:
#     get:
#       summary: Get a number.
#       parameters:
#         - in: path
#           name: num
#           schema:
#             type: array
#             items:
#               type: integer
#           required: true
#           description: Numeric ID of the user to get.